{% set name = "telnyx" %}
{% set version = "2.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/telnyx-{{ version }}.tar.gz
  sha256: 4dd0367fa17826165aa5ec89c6d63b84ca433d62de8af2aaab45c4ee3662a494

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python >=3.6
  run:
    - pynacl
    - python >=3.6
    - requests >=2.20

test:
  imports:
    - telnyx
    - telnyx.api_resources
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/team-telnyx/telnyx-python
  summary: Python bindings for the Telnyx API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kcemenike
