{% set name = "telnyx" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/telnyx-{{ version }}.tar.gz
  sha256: 1acfe3a360917f634c575faab1b61295a6351e92988c95b4fd49d6cc6a766f13

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python {{ python_min }}
  run:
    - pynacl
    - python >={{ python_min }}
    - requests >=2.20

test:
  imports:
    - telnyx
    - telnyx.api_resources
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/team-telnyx/telnyx-python
  summary: Python bindings for the Telnyx API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kcemenike
